// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/volleynati-branding/EditorialAccessibility.tsx": () => import("../components/mockups/volleynati-branding/EditorialAccessibility.tsx"),
  "./components/mockups/volleynati-branding/EditorialAffordance.tsx": () => import("../components/mockups/volleynati-branding/EditorialAffordance.tsx"),
  "./components/mockups/volleynati-branding/EditorialCommunity.tsx": () => import("../components/mockups/volleynati-branding/EditorialCommunity.tsx"),
  "./components/mockups/volleynati-branding/EditorialHierarchy.tsx": () => import("../components/mockups/volleynati-branding/EditorialHierarchy.tsx"),
  "./components/mockups/volleynati-branding/NightTournament.tsx": () => import("../components/mockups/volleynati-branding/NightTournament.tsx"),
  "./components/mockups/volleynati-branding/StreetFestival.tsx": () => import("../components/mockups/volleynati-branding/StreetFestival.tsx")
};
